# Generated by Django 5.2.4 on 2025-07-23 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project (maximum 200 characters)', max_length=200, verbose_name='Project name')),
                ('image', models.ImageField(blank=True, help_text='Representative image of the project', null=True, upload_to='projects/images/', verbose_name='Project image')),
                ('description', models.TextField(help_text='Detailed description of the project', verbose_name='Description')),
                ('link', models.URLField(blank=True, help_text='URL of the project (GitHub, demo, etc.)', null=True, validators=[django.core.validators.URLValidator()], verbose_name='Project link')),
                ('techs_used', models.TextField(blank=True, help_text='List of technologies, frameworks and tools used', verbose_name='Technologies used')),
                ('short_description', models.CharField(blank=True, help_text='Brief description of the project (maximum 300 characters)', max_length=300, verbose_name='Short description')),
                ('github_url', models.URLField(blank=True, help_text='Link to the GitHub repository', null=True, validators=[django.core.validators.URLValidator()], verbose_name='GitHub URL')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the project is active and visible', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
