# Generated by Django 5.2.4 on 2025-07-23 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person sending the message (maximum 100 characters)', max_length=100, verbose_name='Name')),
                ('phone', models.CharField(blank=True, help_text='Phone number for contact (maximum 20 characters)', max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(help_text='Email address for contact', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email address')),
                ('message', models.TextField(help_text='Content of the contact message', verbose_name='Message')),
                ('subject', models.CharField(blank=True, help_text='Subject of the message (maximum 200 characters)', max_length=200, verbose_name='Subject')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates if the message has been read', verbose_name='Read')),
                ('is_responded', models.BooleanField(default=False, help_text='Indicates if a response has been sent', verbose_name='Responded')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the message was first read', null=True, verbose_name='Read at')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the response was sent', null=True, verbose_name='Responded at')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
