# Generated by Django 5.2.4 on 2025-08-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
